// lib/summary.mjs -- the rolling summary: the only history the brain ever sees.
//
// Deterministic by construction, so compaction never costs tokens and never
// silently drops a blocker. It is built exclusively from structured fields
// (card.summaryOneLine, verdict.summaryForRolling), which means raw logs cannot
// physically reach it.
import { existsSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { paths, readJsonl, readJson, listQueue } from './state.mjs';
import { loadBudget, budgetView } from './budget.mjs';

/**
 * The cards the brain has actually judged.
 *
 * Reads the bridge's normalized `*.accepted.json` copies, not the executor's
 * `*.result.json` working documents -- those are rewritten on every rework
 * attempt and may hold a card that was never submitted.
 */
export function completedCards(cfg) {
  const dir = paths(cfg).cards;
  if (!existsSync(dir)) return [];
  const out = [];
  for (const f of readdirSync(dir)) {
    if (!f.endsWith('.accepted.json')) continue;
    const card = readJson(join(dir, f), null);
    if (card) out.push(card);
  }
  return out;
}

export function recentVerdicts(cfg, limit = 10) {
  const all = readJsonl(paths(cfg).ledger).filter((r) => r.kind === 'verdict');
  return all.slice(-limit);
}

export function buildStateBlock(cfg, state) {
  const budget = loadBudget(cfg);
  const queue = listQueue(cfg);
  const counts = { pending: 0, in_progress: 0, submitted: 0, accepted: 0 };
  for (const t of queue) counts[t.state] = (counts[t.state] ?? 0) + 1;

  const gate = (used, limit) => `${used}/${limit}`;
  return [
    `run_id: ${state.runId ?? '(none)'}`,
    `run_status: ${state.status}${state.stopReason ? ` (${state.stopReason})` : ''}`,
    `round: ${gate(state.rounds, cfg.budgets.maxRounds)}   calls_this_run: ${gate(state.turns, cfg.budgets.maxTurnsTotal)}`,
    `today (${budget.day}): requests ${gate(budget.requests, cfg.budgets.maxRequestsPerDay)}, tokens ${gate(budget.tokens, cfg.budgets.maxTokensPerDay)}`,
    `queue: ${queue.length} total -> ${queue.map((t) => `${t.taskId}:${t.state}`).join(', ') || '(empty)'}`,
    `current_task: ${state.currentTaskId ?? '(none)'}`,
    `last_verdict: ${state.lastVerdict ? `${state.lastVerdict.action} on ${state.lastVerdict.taskId}` : '(none)'}`,
  ].join('\n');
}

export function renderRollingSummary(cfg, state, { cardsLimit, verdictLimit } = {}) {
  const maxChars = cfg.summary.rollingMaxChars;
  const keepCards = cardsLimit ?? cfg.summary.cardsKept;
  const keepVerdicts = verdictLimit ?? 8;

  const tasks = new Map(listQueue(cfg).map((t) => [t.taskId, t]));

  const cardLines = completedCards(cfg)
    .sort((a, b) => String(a.taskId).localeCompare(String(b.taskId)))
    .slice(-keepCards)
    .map((c) => {
      const t = tasks.get(c.taskId);
      const title = t?.title ? ` (${truncate(t.title, 60)})` : '';
      return `- ${c.taskId}${title} [${c.status}] ${truncate(c.summaryOneLine, cfg.summary.oneLineMaxChars)}` +
        (c.blockers?.length ? ` | blockers: ${c.blockers.map((b) => truncate(b, 80)).join('; ')}` : '');
    });

  const verdictLines = recentVerdicts(cfg, keepVerdicts).map((v) =>
    `- round ${v.round ?? '?'} ${v.taskId ?? '-'} -> ${v.action}: ${truncate(v.reason ?? '', 120)}`);

  const openBlockers = completedCards(cfg)
    .filter((c) => (c.blockers?.length ?? 0) > 0 && c.status !== 'completed')
    .slice(-5)
    .map((c) => `- ${c.taskId}: ${c.blockers.map((b) => truncate(b, 100)).join('; ')}`);

  const sections = [
    ['## State', buildStateBlock(cfg, state)],
    ['## Completed work (newest kept)', cardLines.length ? cardLines.join('\n') : '(none yet)'],
    ['## Decision history', verdictLines.length ? verdictLines.join('\n') : '(none yet)'],
    ['## Open blockers', openBlockers.length ? openBlockers.join('\n') : '(none)'],
  ];

  // Budget-aware tail trimming: drop the oldest card lines first, never a blocker.
  let body = sections.map(([h, b]) => `${h}\n${b}`).join('\n\n');
  let dropped = 0;
  while (body.length > maxChars && cardLines.length - dropped > 1) {
    dropped++;
    sections[1][1] = [`(older entries elided: ${dropped})`, ...cardLines.slice(dropped)].join('\n');
    body = sections.map(([h, b]) => `${h}\n${b}`).join('\n\n');
  }
  if (body.length > maxChars) body = `${body.slice(0, maxChars - 32)}\n...(summary truncated)`;

  return body;
}

export function refreshRollingSummary(cfg, state) {
  const body = renderRollingSummary(cfg, state);
  const header = `<!-- rolling summary, regenerated by lib/summary.mjs. Deterministic; no raw logs by construction. -->\n`;
  writeFileSync(paths(cfg).summaryMd, header + body + '\n', 'utf8');
  return body;
}

export function truncate(s, n) {
  const t = String(s ?? '').replace(/\s+/g, ' ').trim();
  return t.length > n ? `${t.slice(0, n - 3)}...` : t;
}
